### PR TITLE
Library provider

### PR DESCRIPTION
**Pull request by jmauro**
Hey,

It would be great if we could use your provider as a library and not only with attributes. 
Let me know if the PR is good enough for you or if I need to change some stuff.

Looking forward to hearing from you

Regards,
JM

### CODE REVIEW

**Comment by davemeekin** [comment]
Hey JM, 

I'll try and get around to reviewing this tomorrow.

Thanks,

Dave

**Comment by jmauro** [comment]
Hey,

Thx

**Comment by davemeekin** [comment]
Hi JM,

All looks good. Just wondering why you removed the default recipe used to install tuned if is not installed?

I don't believe tuned is installed by default on EL 6. I could be wrong though it does seem to pass in Docker.

Is it best practice not to complicate a provider/library by adding recipes to install packages?

Dave

**Comment by jmauro** [comment]
Hey,

If you want to use the provider as a library you don't want to force the user to setup the requirement in a recipe, at least that is what we enforce internally in my company.

You don't need the default recipe since it is build inside the provider: https://github.com/autotraderuk/chef-tuned/pull/2/files#diff-c65bd91a52ef031b866047c7395f4062R80 and I make sure the requirement is always present whenever I used the `tuned-adm` command.

Did answer you question?

Regards,
Jeremy MAURO

**Comment by jmauro** [comment]
Hey me again,

If you don't to break your working `run_list`, I can create a default recipe as follow:
```
# cat attributes/default.rb
default['tuned']['profile'] = {}
default['tuned']['active_profile'] = nil
# cat recipe/default.rb
tuned_profile node['tuned']['active_profile'] do
  action [:create, :enable]
end
```
Could this be something you'd like?

Regards,
Jeremy

**Comment by davemeekin** [comment]
Hi Jeremy,

Thanks for clearing up the 'tuned_requirements' section.
Your approach seems like like the best solution, I'll merge the pull request and bump a new version of the cookbook today. Thanks for working on this with us.

Regards,

Dave

**Pull request merged**
